org: runitest
app: parkinglot
service: parking-lot-service

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

  # IAM permissions for DynamoDB
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:Scan
      Resource:
        - arn:aws:dynamodb:us-east-1:*:table/Tickets

  # REST API setup with API key support
  apiGateway:
    apiKeys:
      - name: parkingApiKey

functions:
  entry:
    handler: entry.handler
    events:
      - http:
          path: entry
          method: post
          private: true

  exit:
    handler: exit.handler
    events:
      - http:
          path: exit
          method: post
          private: true

plugins:
  - serverless-offline

resources:
  Resources:
    TicketsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Tickets
        AttributeDefinitions:
          - AttributeName: ticketId
            AttributeType: S
        KeySchema:
          - AttributeName: ticketId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
